import PlanPage from '@/components/Plan&PricingPage/Plan'
import Head from 'next/head'
import React from 'react'

export default function PlanMainpage() {
  return (
    <div className='plans-and-pricing-maindiv'>
         <Head>
            <title>Plans & Pricing | Jame Consulting</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.png" />  
         </Head>
            <PlanPage/>
    </div>
  )
}
