import React from 'react'
import Head from 'next/head'
import Profile from '@/components/AboutPage/Profile'
import Team from '@/components/AboutPage/Team'

export default function AboutPage() {
  return (
    <div className='aboutpage-maindiv'>
        <Head>
            <title>About | Jame Consulting</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.png" />  
        </Head>
         <Profile/>
         <Team/>
    </div>
  )
}
