import Head from 'next/head'
import { Inter } from 'next/font/google'
import Hero from '@/sections/Hero/Hero'
import Intro from '@/sections/Intro/Intro'
import About from '@/sections/About/About'
import Client from '@/sections/Client/Client'
import Testimonial from '@/sections/Testimonials/Testimonial'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='home-maindiv'>
      <Head>
        <title>Home | Jame Consulting</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />  
      </Head>
          <Hero/>
          <Intro/>
          <About/>
          <Client/>   
          <Testimonial/>
    </div>
  )
}
