import ToolsAndTips from '@/components/ToolsAndTips-UI/ToolsAndTips'
import Head from 'next/head'
import React from 'react'

export default function ToolsandtipsPage() {
  return (
    <div className='tools-and-tips-mainpage'>
        <Head>
            <title> Tools and Tips | Jame Consulting</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.png" />  
        </Head>
        <ToolsAndTips/>
    </div>
  )
}
